## Question 1

**Print the head of the data**

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("loans.csv")

df.head()

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
0,14dd8831-6af5-400b-83ec-68e61888a048,Fully Paid,445412.00,Short Term,709.00,1167493.00,Home Mortgage,Home Improvements,5214.74,17.20,6.00,1.00,228190.00,416746.00,1.00
1,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,Fully Paid,99999999.00,Short Term,741.00,2231892.00,Own Home,Debt Consolidation,29200.53,14.90,18.00,1.00,297996.00,750090.00,0.00
2,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,Fully Paid,347666.00,Long Term,721.00,806949.00,Own Home,Debt Consolidation,8741.90,12.00,9.00,0.00,256329.00,386958.00,0.00
3,89d8cb0c-e5c2-4f54-b056-48a645c543dd,Charged Off,206602.00,Short Term,7290.00,896857.00,Home Mortgage,Debt Consolidation,16367.74,17.30,6.00,0.00,215308.00,272448.00,0.00
4,273581de-85d8-4332-81a5-19b04ce68666,Fully Paid,217646.00,Short Term,730.00,1184194.00,Home Mortgage,Debt Consolidation,10855.08,19.60,13.00,1.00,122170.00,272052.00,1.00

**Remove (filter out) loans that are unrealistically large**

In [ ]:
large_loans = df[df['Current Loan Amount'] < 99999999]

large_loans

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
0,14dd8831-6af5-400b-83ec-68e61888a048,Fully Paid,445412.00,Short Term,709.00,1167493.00,Home Mortgage,Home Improvements,5214.74,17.20,6.00,1.00,228190.00,416746.00,1.00
2,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,Fully Paid,347666.00,Long Term,721.00,806949.00,Own Home,Debt Consolidation,8741.90,12.00,9.00,0.00,256329.00,386958.00,0.00
3,89d8cb0c-e5c2-4f54-b056-48a645c543dd,Charged Off,206602.00,Short Term,7290.00,896857.00,Home Mortgage,Debt Consolidation,16367.74,17.30,6.00,0.00,215308.00,272448.00,0.00
4,273581de-85d8-4332-81a5-19b04ce68666,Fully Paid,217646.00,Short Term,730.00,1184194.00,Home Mortgage,Debt Consolidation,10855.08,19.60,13.00,1.00,122170.00,272052.00,1.00
5,8af915d9-9e91-44a0-b5a2-564a45c12089,Fully Paid,548746.00,Short Term,678.00,2559110.00,Rent,Debt Consolidation,18660.28,22.60,4.00,0.00,437171.00,555038.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70313,3b2a09bb-3467-4d2f-bd8f-260fdc5760be,Fully Paid,179454.00,Short Term,708.00,1356068.00,Home Mortgage,Debt Consolidation,22318.54,22.70,25.00,0.00,387410.00,1705616.00,0.00
70314,38530a21-5a57-47f5-9aaa-b4475b1db345,Fully Paid,781022.00,Short Term,741.00,2582404.00,Home Mortgage,Debt Consolidation,51648.08,26.30,25.00,0.00,669180.00,2299198.00,0.00
70316,8506a4e9-af7d-47d2-a1bf-7ea2c41858f0,Fully Paid,210584.00,Short Term,719.00,783389.00,Home Mortgage,Other,3727.61,17.40,6.00,0.00,456.00,259160.00,0.00
70318,e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7,Fully Paid,103136.00,Short Term,742.00,1150545.00,Rent,Debt Consolidation,7315.57,18.80,12.00,1.00,109554.00,537548.00,1.00
70319,81ab928b-d1a5-4523-9a3c-271ebb01b4fb,Fully Paid,530332.00,Short Term,746.00,1717524.00,Rent,Debt Consolidation,9890.07,15.00,8.00,0.00,404225.00,738254.00,0.00

**Which loan(s) have the highest Current Credit Balance?**

In [ ]:
largest = df.nlargest(58893,'Current Credit Balance')
largest

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
12459,c194cb68-1c4d-4bba-8433-98cf4e0f357d,Charged Off,762850.00,Short Term,7320.00,7529320.00,Home Mortgage,other,205801.35,32.50,28.00,0.00,32878968.00,98627914.00,0.00
34554,c4c387b5-7708-4f96-bf0a-6b23a60f196c,Fully Paid,761684.00,Long Term,691.00,4698700.00,Home Mortgage,Debt Consolidation,124907.14,36.50,27.00,0.00,12986956.00,20238944.00,0.00
49789,007ebd31-1453-4d04-97f4-97737e01c608,Fully Paid,235312.00,Long Term,724.00,6580802.00,Own Home,Debt Consolidation,120647.91,33.10,10.00,0.00,12746397.00,14598408.00,0.00
68019,3dbc3b41-ad17-4b11-aa78-246c3afdc191,Fully Paid,773784.00,Long Term,710.00,5155137.00,Home Mortgage,Debt Consolidation,101813.97,22.90,12.00,0.00,11796435.00,16677694.00,0.00
38748,9dfa56f4-ced5-4cce-ad91-076068c1910b,Fully Paid,760298.00,Short Term,733.00,8629876.00,Home Mortgage,Home Improvements,87017.91,24.10,22.00,0.00,11361924.00,20333720.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32168,4d66dd9a-4495-43c2-9090-df85fc493245,Fully Paid,760848.00,Long Term,741.00,1689651.00,Home Mortgage,Debt Consolidation,16797.90,17.70,15.00,0.00,82137.00,1001110.00,0.00
45198,b2954422-a9ff-4479-9ba7-386e4e17468e,Fully Paid,143726.00,Short Term,742.00,872784.00,Own Home,Medical Bills,17019.25,8.50,6.00,0.00,82137.00,161744.00,0.00
68393,62071613-1c9d-4177-8444-f12c31e456ec,Fully Paid,132044.00,Short Term,743.00,627190.00,Rent,Debt Consolidation,2947.85,13.90,4.00,0.00,82137.00,356224.00,0.00
24103,ee6331d0-a9bc-458c-9cfd-30efc0c96091,Fully Paid,99999999.00,Long Term,635.00,1401972.00,Home Mortgage,Debt Consolidation,15305.07,19.90,6.00,0.00,82099.00,288948.00,0.00
61587,c0114165-9986-4c31-842b-c1d4adff9752,Fully Paid,99999999.00,Short Term,742.00,952698.00,Rent,Debt Consolidation,16592.70,12.40,13.00,0.00,82099.00,265562.00,0.00

**Which loan(s) have the smallest Annual Income?**

In [ ]:
smallest = df.nsmallest(58893,'Annual Income')
smallest

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
48729,fdda52f3-bbfa-45da-80b5-2bd9b68638ed,Charged Off,30448.00,Short Term,736.00,76627.00,Rent,Debt Consolidation,845.50,9.50,8.00,0.00,28177.00,147598.00,0.00
38169,9ed28b3a-c3a9-4ae4-93e6-3de7ff42f64e,Fully Paid,61490.00,Short Term,662.00,81092.00,Rent,Educational Expenses,0.00,11.00,6.00,0.00,0.00,0.00,0.00
49094,8f65d638-5789-46af-99f2-72c4d03c9321,Fully Paid,99999999.00,Short Term,737.00,94867.00,Own Home,Debt Consolidation,2656.01,8.50,11.00,0.00,86925.00,190982.00,0.00
70054,a8539cc1-63d7-4e2e-bddb-4dd1a074182c,Fully Paid,99999999.00,Short Term,745.00,106533.00,Rent,Other,329.27,11.80,4.00,0.00,10963.00,147598.00,0.00
7624,241e16a3-c198-4d8e-8dad-c927fd7c7d24,Fully Paid,34342.00,Short Term,715.00,111245.00,Own Home,Other,463.60,29.70,3.00,0.00,6840.00,264044.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14247,7af640a0-ecda-4802-a1ab-3aa34bb9b83d,Fully Paid,222574.00,Long Term,734.00,1922230.00,Home Mortgage,Debt Consolidation,8073.29,14.80,9.00,0.00,60021.00,180488.00,0.00
48079,9a626b8d-a754-436f-9052-64147c898aeb,Fully Paid,133540.00,Short Term,740.00,1922230.00,Own Home,Debt Consolidation,49497.47,24.00,25.00,0.00,284392.00,1086778.00,0.00
68835,0197dd94-b587-440d-98c3-e3e89e2e0878,Fully Paid,333872.00,Short Term,747.00,1922230.00,Home Mortgage,Home Improvements,6695.79,35.30,9.00,0.00,11590.00,1491248.00,0.00
31520,39b13633-be67-464c-9fc8-68156701d2e3,Charged Off,340428.00,Short Term,719.00,1922306.00,Rent,Debt Consolidation,41489.73,25.00,17.00,0.00,508991.00,1336434.00,0.00
43355,a0803705-a82b-452a-bb3e-8a95658fcc92,Charged Off,717398.00,Short Term,676.00,1922306.00,Home Mortgage,Debt Consolidation,32358.71,19.40,17.00,0.00,513190.00,669922.00,0.00

**Use describe(), and answer the following questions**

In [ ]:

pd.set_option ('display.float_format','{:.2f}'.format)

describe = df['Current Loan Amount'].describe()
describe

count      70321.00
mean    16512589.51
std     36777479.40
min        15422.00
25%       191268.00
50%       327140.00
75%       568942.00
max     99999999.00
Name: Current Loan Amount, dtype: float64

**Create a new field into your dataset called Actual Annual Income.**

In [ ]:
df['Actual Annual Income'] = df['Annual Income']- (12 * df['Monthly Debt'])
df

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Actual Annual Income
0,14dd8831-6af5-400b-83ec-68e61888a048,Fully Paid,445412.00,Short Term,709.00,1167493.00,Home Mortgage,Home Improvements,5214.74,17.20,6.00,1.00,228190.00,416746.00,1.00,1104916.12
1,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,Fully Paid,99999999.00,Short Term,741.00,2231892.00,Own Home,Debt Consolidation,29200.53,14.90,18.00,1.00,297996.00,750090.00,0.00,1881485.64
2,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,Fully Paid,347666.00,Long Term,721.00,806949.00,Own Home,Debt Consolidation,8741.90,12.00,9.00,0.00,256329.00,386958.00,0.00,702046.20
3,89d8cb0c-e5c2-4f54-b056-48a645c543dd,Charged Off,206602.00,Short Term,7290.00,896857.00,Home Mortgage,Debt Consolidation,16367.74,17.30,6.00,0.00,215308.00,272448.00,0.00,700444.12
4,273581de-85d8-4332-81a5-19b04ce68666,Fully Paid,217646.00,Short Term,730.00,1184194.00,Home Mortgage,Debt Consolidation,10855.08,19.60,13.00,1.00,122170.00,272052.00,1.00,1053933.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70316,8506a4e9-af7d-47d2-a1bf-7ea2c41858f0,Fully Paid,210584.00,Short Term,719.00,783389.00,Home Mortgage,Other,3727.61,17.40,6.00,0.00,456.00,259160.00,0.00,738657.68
70317,06eba04f-58fc-424a-b666-ed72aa008900,Fully Paid,99999999.00,Short Term,732.00,1289416.00,Rent,Debt Consolidation,13109.05,9.40,22.00,0.00,153045.00,509234.00,0.00,1132107.40
70318,e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7,Fully Paid,103136.00,Short Term,742.00,1150545.00,Rent,Debt Consolidation,7315.57,18.80,12.00,1.00,109554.00,537548.00,1.00,1062758.16
70319,81ab928b-d1a5-4523-9a3c-271ebb01b4fb,Fully Paid,530332.00,Short Term,746.00,1717524.00,Rent,Debt Consolidation,9890.07,15.00,8.00,0.00,404225.00,738254.00,0.00,1598843.16
70320,c63916c6-6d46-47a9-949a-51d09af4414f,Fully Paid,99999999.00,Short Term,743.00,935180.00,Own Home,Debt Consolidation,9118.10,13.00,4.00,1.00,45600.00,91014.00,1.00,825762.80

**How many loans are "Long term"?**

In [ ]:
long = df['Term'].value_counts()['Long Term']
long

np.int64(19064)

**What are the 3 most common loan purposes?**

In [ ]:
common_purposes = df['Purpose'].value_counts().head(3)
common_purposes

Purpose
Debt Consolidation    55505
other                  4196
Home Improvements      4108
Name: count, dtype: int64

**Small extra task: There seems to be two versions of "other" in the data for loan purpose**

In [ ]:
df['Purpose'] = df['Purpose'].replace("other","Other")
df['Purpose'].value_counts()

Purpose
Debt Consolidation      55505
Other                    6464
Home Improvements        4108
Business Loan            1063
Buy a Car                 920
Medical Bills             774
Buy House                 469
major_purchase            260
Take a Trip               237
small_business            200
moving                    110
wedding                    76
Educational Expenses       68
vacation                   61
renewable_energy            6
Name: count, dtype: int64

**Small extra task: study the distribution of "Number of Credit Problems" by using value_counts(). Explain your findings**

In [ ]:
df['Number of Credit Problems'].value_counts()


# Explanation :  Most customers has no credit problems and fewer has some issues. but there least number of customers who has with a higher number of credit problems

Number of Credit Problems
0.00    60643
1.00     8376
2.00      896
3.00      261
4.00       87
5.00       37
6.00       12
7.00        6
8.00        3
Name: count, dtype: int64

**How many unique Home Ownership -options there are in the dataset?**

In [ ]:
df['Home Ownership'].nunique()

3

##  Other small extra tasks:

**How many loaners have more than 1 bankruptcy?**

In [ ]:
bankrupt = (df['Bankruptcies'] > 1).sum()
bankrupt

np.int64(376)

**How many Short Term loans are for Home Improvements?**

In [ ]:
short_term= df[df['Term'] == 'Short Term']

home= short_term['Purpose'].value_counts()['Home Improvements']
home

np.int64(2859)

## Question 2

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("purchases.csv")

df

,Purchase Date,Purchase Order Number,Acquisition Type,Acquisition Method,Department Name,Supplier Name,Item Name,Item Description,Quantity,Unit Price,Total Price,Commodity Title,Class Title,Family Title,Segment Title
0,08/31/2012,4500149558,Other Goods,Formal Competitive,"Corrections and Rehabilitation, Department of",Fresno Produce Inc.,JALAPENO,JALAPENO,40.00,$0.60,24.00,Jalapeno peppers,Peppers,Fresh vegetables,Food Beverage and Tobacco Products
1,10/18/2012,4500156192,Other Goods,Informal Competitive,"Corrections and Rehabilitation, Department of",PETER GIAMMANCO,produce,"red apples, banana,",1.00,"$12,587.05",12587.05,Ida red apples,Apples,Fresh fruits,Food Beverage and Tobacco Products
2,10/17/2012,4500156124,Other Goods,Fair and Reasonable,Correctional Health Care Services,OSHA Review Inc,magazine,magazine,1.00,$199.00,199.00,Magazines,Printed publications,Printed media,Published Products
3,10/24/2012,S2556056,Other Goods,Informal Competitive,"Parks & Recreation, Department of",Agco Hay LLC,hay,Bale's of rice straw,1000.00,$4.95,4950.00,Hay,Livestock feed,Animal feed,Live Plant and Animal Material and Accessories...
4,11/14/2012,4500159228,Other Goods,Informal Competitive,"Corrections and Rehabilitation, Department of",Prison Industry Authority,COFFEE,INSTANT COFFEE AND BULK,14686.50,$1.00,14686.50,Coffee,Coffee and tea,Beverages,Food Beverage and Tobacco Products
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62468,08/23/2013,S3863002,Other Goods,Statewide Contract,"Parks & Recreation, Department of",Technology Integration Group,HP Black Toner,HP Black Toner,3.00,$100.50,301.50,Printer or facsimile toner,Printer and facsimile and photocopier supplies,Office machines and their supplies and accesso...,Office Equipment and Accessories and Supplies
62469,08/23/2013,S3863002,Other Goods,Statewide Contract,"Parks & Recreation, Department of",Technology Integration Group,Toner Cartridge - YELLOW,Toner YELLOW (Printer),2.00,$245.00,490.00,Printer or facsimile toner,Printer and facsimile and photocopier supplies,Office machines and their supplies and accesso...,Office Equipment and Accessories and Supplies
62470,08/23/2013,S3863002,Other Goods,Statewide Contract,"Parks & Recreation, Department of",Technology Integration Group,Toner Cartridge - CYAN,Toner - CYAN (Printer),2.00,$245.00,490.00,Printer or facsimile toner,Printer and facsimile and photocopier supplies,Office machines and their supplies and accesso...,Office Equipment and Accessories and Supplies
62471,08/23/2013,2U3H1109,Other Services,Emergency Purchase,"Forestry and Fire Protection, Department of",Lakeview Petroleum,FUEL TRUCK,FUEL TENDER 4500 GL,1.00,"$20,475.00",20475.00,Equipment usage fee,Refuse disposal and treatment fees,Refuse disposal and treatment,Industrial Cleaning Services
62472,08/23/2013,4500195481,Other Goods,Informal Competitive,Correctional Health Care Services,"Bay Medical Co., Inc",Transfer Labels,Industrial Thermal Transfer Labels,1.00,"$1,181.44",1181.44,Affinity labels,Indicators and Reagents,Additives,Chemicals including Bio Chemicals and Gas Mate...

**What was the total price sum of the Purchase Order Number 018H2015? (14 rows in total)**

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("purchases.csv")

sum1 = df[df['Purchase Order Number']=='018H2015']['Total Price'].sum()
sum1

np.float64(1245.0400000000002)

**What is the item name and description of the purchased item with the Purchase Order Number 3176273?**

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("purchases.csv")


item = data[data['Purchase Order Number']=='3176273'][['Item Name','Item Description']]
item

NameError: name 'data' is not defined

**How many occasions (rows) of purchase data happened during the year 2013?**

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("purchases.csv")

df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])

df['Year'] = df['Purchase Date'].dt.year

occasion2013 = len(df[df['Year'] == 2013])

occasion2013

**What are the 5 most common Departments in the data?**

In [ ]:

Department = df['Department Name'].value_counts().head(5)
Department

Department Name
Corrections and Rehabilitation, Department of    10858
Correctional Health Care Services                 6591
Water Resources, Department of                    4566
Forestry and Fire Protection, Department of       4513
State Hospitals, Department of                    4258
Name: count, dtype: int64

**Replace the $-sign in the Unit Price –column with an empty string,and convert the value to float**

In [ ]:
df['Unit Price'] = df['Unit Price'].str.replace('$', '').astype(float)
df

**Smaller extra tasks**

In [ ]:
# How many purchases in the data were IT Goods and had the total price of more than 50000 dollars?

IT = df[(df['Acquisition Type'] == 'IT Goods') & (df['Total Price'] > 50000)]
count = len(IT)
count

In [ ]:

# How many of the purchases have anything to do with IT? 

it_purchases = df[(df['Acquisition Type'] == 'IT Goods') | 
                  (df['Acquisition Type'] == 'IT Services') |
                  (df['Acquisition Type'] == 'IT Telecommunications')]
count = len(it_purchases)
count

## Question 3

In [ ]:
import numpy as np
import pandas as pd

df= pd.read_csv("salaries_india.csv")

df

,Row ID,Company Name,Rating,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,79417,Unacademy,Good,Android Developer,2046000.00,3,Bangalore,Full Time,Mobile
1,79419,Appoids Tech Solutions,Good,Android Developer,1227600.00,3,Bangalore,Full Time,Mobile
2,79424,Endeavour Software Technologies,Good,Android Developer,1227600.00,3,Bangalore,Full Time,Mobile
3,79427,Wibmo,Good,Android Developer,1841400.00,2,Bangalore,Full Time,Mobile
4,79429,Bookmyshow,Good,Android Developer,1227600.00,2,Bangalore,Full Time,Mobile
...,...,...,...,...,...,...,...,...,...
10782,102163,Full Time Soluções em Serviços Financeiros,Good,Web Developer,2406096.00,1,Bangalore,Full Time,Web
10783,102167,SwervePoint,Good,Web Developer,1227600.00,1,Bangalore,Full Time,Web
10784,102168,rtCamp,Good,Web Developer,1432200.00,1,Bangalore,Full Time,Web
10785,102173,Blu Ocean Innovations,Excellent,Web Developer - Intern,967572.00,1,Bangalore,Intern,Web
10786,102178,Unicon Systems,Good,Web Developer,1023000.00,1,Bangalore,Full Time,Web

**Remove the columns "Row ID" and "Job Title"**

In [ ]:
import numpy as np
import pandas as pd

df= pd.read_csv("salaries_india.csv")


df = df.drop(columns=['Row ID', 'Job Title'])
df

,Company Name,Rating,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,Unacademy,Good,2046000.00,3,Bangalore,Full Time,Mobile
1,Appoids Tech Solutions,Good,1227600.00,3,Bangalore,Full Time,Mobile
2,Endeavour Software Technologies,Good,1227600.00,3,Bangalore,Full Time,Mobile
3,Wibmo,Good,1841400.00,2,Bangalore,Full Time,Mobile
4,Bookmyshow,Good,1227600.00,2,Bangalore,Full Time,Mobile
...,...,...,...,...,...,...,...
10782,Full Time Soluções em Serviços Financeiros,Good,2406096.00,1,Bangalore,Full Time,Web
10783,SwervePoint,Good,1227600.00,1,Bangalore,Full Time,Web
10784,rtCamp,Good,1432200.00,1,Bangalore,Full Time,Web
10785,Blu Ocean Innovations,Excellent,967572.00,1,Bangalore,Intern,Web
10786,Unicon Systems,Good,1023000.00,1,Bangalore,Full Time,Web

**How large are the highest salaries in this dataset?**

In [ ]:
outliers = df['Salary'].value_counts().sort_index(ascending=False).head(10)
outliers

# AI was used to find the answer

Salary
9284422.50    1
8644117.50    1
8421043.50    1
8109153.00    2
8010090.00    4
8003812.50    2
7803378.00    1
7797262.50    1
7733880.00    5
7683660.00    1
Name: count, dtype: int64

In [ ]:
# Remove all salaries that are too high

cutoff = df['Salary'].quantile(0.99)
filtered_df = df.loc[df['Salary'] <= cutoff]
salary_count = len(filtered_df)
salary_count

10688

**Handle "Employment Status" as a binary variable**

In [ ]:
from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()

df['Employment Status'] = encoder.fit_transform(df['Employment Status'])


df.head()

**Handle "Rating" as an ordinal variable**

In [ ]:
rating_encoding = {'Poor': 1, 'Average': 2, 'Good': 3, 'Excellent': 4}
df['Rating_Encoded'] = df['Rating'].replace(rating_encoding)
encoded_result = df[['Rating', 'Rating_Encoded']]
encoded_result 

# used AI to find the answer. But code did not work.

**Handle "Job Roles" and "Location" as NOMINAL categories**

In [ ]:
df_encoded = pd.get_dummies(df, columns=['Job Roles', 'Location'])
last_nominal = df_encoded
last_nominal

,Row ID,Company Name,Rating,Job Title,Salary,Salaries Reported,Employment Status,Rating_Ordinal,Employment_Status_Numeric,Location_Code,Job_Roles_Code,Job Roles_Backend,Job Roles_Full stack,Job Roles_Mobile,Job Roles_Web,Location_Bangalore,Location_Chennai,Location_Hyderabad,Location_New Delhi,Location_Pune
0,79417,Unacademy,Good,Android Developer,2046000.00,3,Full Time,3.00,0,0,0,False,False,True,False,True,False,False,False,False
1,79419,Appoids Tech Solutions,Good,Android Developer,1227600.00,3,Full Time,3.00,0,0,0,False,False,True,False,True,False,False,False,False
2,79424,Endeavour Software Technologies,Good,Android Developer,1227600.00,3,Full Time,3.00,0,0,0,False,False,True,False,True,False,False,False,False
3,79427,Wibmo,Good,Android Developer,1841400.00,2,Full Time,3.00,0,0,0,False,False,True,False,True,False,False,False,False
4,79429,Bookmyshow,Good,Android Developer,1227600.00,2,Full Time,3.00,0,0,0,False,False,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10782,102163,Full Time Soluções em Serviços Financeiros,Good,Web Developer,2406096.00,1,Full Time,3.00,0,0,2,False,False,False,True,True,False,False,False,False
10783,102167,SwervePoint,Good,Web Developer,1227600.00,1,Full Time,3.00,0,0,2,False,False,False,True,True,False,False,False,False
10784,102168,rtCamp,Good,Web Developer,1432200.00,1,Full Time,3.00,0,0,2,False,False,False,True,True,False,False,False,False
10785,102173,Blu Ocean Innovations,Excellent,Web Developer - Intern,967572.00,1,Intern,4.00,1,0,2,False,False,False,True,True,False,False,False,False
10786,102178,Unicon Systems,Good,Web Developer,1023000.00,1,Full Time,3.00,0,0,2,False,False,False,True,True,False,False,False,False

**Analyze the correlation matrix from the point of view of Salary**

In [ ]:
numeric_df = df.select_dtypes(include=['float64', 'int64'])
corr_data = numeric_df.corr()
salary_corr_values = corr_data.loc[:, ['Salary']].sort_values('Salary', ascending=False)
salary_corr_values

                           Salary
Salary                       1.00
Job_Roles_Code               0.25
Rating_Ordinal               0.19
Row ID                       0.10
Salaries Reported            0.09
Employment_Status_Numeric   -0.08
Location_Code               -0.27

**Which variables have the biggest impact on a salary?**

Looking at the correlation matrix, Rating_Ordinal shows the strongest relationship with salary at 0.192, while other variables like Row ID and Salaries Reported have very weak correlations below 0.1.

**Try also experimenting with the outlier cutoff point,does it affect the correlations if you cut more high salaries out of the data in the earlier phase?**

In [ ]:
corr_all = df['Salary'].corr(df['Rating_Ordinal'])
df_clean = df[df['Salary'] <= 500000]
corr_clean = df_clean['Salary'].corr(df_clean['Rating_Ordinal'])

corr_comparison = pd.DataFrame({'Type': ['All Data', 'After Outlier Removal'], 'Correlation': [corr_all, corr_clean]})
corr_comparison

                    Type  Correlation
0               All Data         0.19
1  After Outlier Removal         0.55